// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Na struct {
	ID          int32
	Nasname     string
	Shortname   sql.NullString
	Type        sql.NullString
	Ports       sql.NullInt32
	Secret      string
	Server      sql.NullString
	Community   sql.NullString
	Description sql.NullString
}

type Nasreload struct {
	Nasipaddress string
	Reloadtime   time.Time
}

type Radacct struct {
	Radacctid           int64
	Acctsessionid       string
	Acctuniqueid        string
	Username            string
	Groupname           string
	Realm               sql.NullString
	Nasipaddress        string
	Nasportid           sql.NullString
	Nasporttype         sql.NullString
	Acctstarttime       sql.NullTime
	Acctupdatetime      sql.NullTime
	Acctstoptime        sql.NullTime
	Acctinterval        sql.NullInt32
	Acctsessiontime     sql.NullInt32
	Acctauthentic       sql.NullString
	ConnectinfoStart    sql.NullString
	ConnectinfoStop     sql.NullString
	Acctinputoctets     sql.NullInt64
	Acctoutputoctets    sql.NullInt64
	Calledstationid     string
	Callingstationid    string
	Acctterminatecause  string
	Servicetype         sql.NullString
	Framedprotocol      sql.NullString
	Framedipaddress     string
	Framedipv6address   string
	Framedipv6prefix    string
	Framedinterfaceid   string
	Delegatedipv6prefix string
	Class               sql.NullString
}

type Radcheck struct {
	ID        uint32
	Username  string
	Attribute string
	Op        string
	Value     string
}

type Radgroupcheck struct {
	ID        uint32
	Groupname string
	Attribute string
	Op        string
	Value     string
}

type Radgroupreply struct {
	ID        uint32
	Groupname string
	Attribute string
	Op        string
	Value     string
}

type Radpostauth struct {
	ID       int32
	Username string
	Pass     string
	Reply    string
	Authdate time.Time
	Class    string
}

type Radreply struct {
	ID        uint32
	Username  string
	Attribute string
	Op        string
	Value     string
}

type Radusergroup struct {
	ID        uint32
	Username  string
	Groupname string
	Priority  int32
}
