// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createGroupName = `-- name: CreateGroupName :execresult
INSERT INTO radgroupreply (groupname, attribute, op, value) VALUES (?, ?, "=", ?)
`

type CreateGroupNameParams struct {
	Groupname string
	Attribute string
	Value     string
}

func (q *Queries) CreateGroupName(ctx context.Context, arg CreateGroupNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGroupName, arg.Groupname, arg.Attribute, arg.Value)
}

const createProfile = `-- name: CreateProfile :execresult
INSERT INTO radusergroup (username, groupname, priority) VALUES (?, ?, ?)
`

type CreateProfileParams struct {
	Username  string
	Groupname string
	Priority  int32
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProfile, arg.Username, arg.Groupname, arg.Priority)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO radcheck(username, attribute, op, value) VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	Username  string
	Attribute string
	Op        string
	Value     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Attribute,
		arg.Op,
		arg.Value,
	)
}

const deleteGroupName = `-- name: DeleteGroupName :exec
DELETE FROM radgroupreply WHERE id = ?
`

func (q *Queries) DeleteGroupName(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, deleteGroupName, id)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM radusergroup WHERE id = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM radcheck WHERE username = ?
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, username)
	return err
}

const getGroupNameByID = `-- name: GetGroupNameByID :one
SELECT id, groupname, attribute, op, value FROM radgroupreply WHERE id = ? LIMIT 1
`

func (q *Queries) GetGroupNameByID(ctx context.Context, id uint32) (Radgroupreply, error) {
	row := q.db.QueryRowContext(ctx, getGroupNameByID, id)
	var i Radgroupreply
	err := row.Scan(
		&i.ID,
		&i.Groupname,
		&i.Attribute,
		&i.Op,
		&i.Value,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, username, groupname, priority FROM radusergroup WHERE id = ? LIMIT 1
`

func (q *Queries) GetProfileByID(ctx context.Context, id uint32) (Radusergroup, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i Radusergroup
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Groupname,
		&i.Priority,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, attribute, op, value FROM radcheck WHERE id = ? AND attribute = "User-Profile" LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uint32) (Radcheck, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i Radcheck
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Attribute,
		&i.Op,
		&i.Value,
	)
	return i, err
}

const listGroupNames = `-- name: ListGroupNames :many
SELECT id, groupname, attribute, op, value FROM radgroupreply
`

func (q *Queries) ListGroupNames(ctx context.Context) ([]Radgroupreply, error) {
	rows, err := q.db.QueryContext(ctx, listGroupNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Radgroupreply
	for rows.Next() {
		var i Radgroupreply
		if err := rows.Scan(
			&i.ID,
			&i.Groupname,
			&i.Attribute,
			&i.Op,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, username, groupname, priority FROM radusergroup
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Radusergroup, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Radusergroup
	for rows.Next() {
		var i Radusergroup
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Groupname,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, attribute, op, value FROM radcheck WHERE attribute = "User-Profile"
`

func (q *Queries) ListUsers(ctx context.Context) ([]Radcheck, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Radcheck
	for rows.Next() {
		var i Radcheck
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Attribute,
			&i.Op,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupName = `-- name: UpdateGroupName :execresult
UPDATE radgroupreply SET groupname = ?, attribute = ?, value = ? WHERE id = ?
`

type UpdateGroupNameParams struct {
	Groupname string
	Attribute string
	Value     string
	ID        uint32
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGroupName,
		arg.Groupname,
		arg.Attribute,
		arg.Value,
		arg.ID,
	)
}

const updateProfile = `-- name: UpdateProfile :execresult
UPDATE radusergroup SET username = ?, groupname = ?, priority = ? WHERE id = ?
`

type UpdateProfileParams struct {
	Username  string
	Groupname string
	Priority  int32
	ID        uint32
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProfile,
		arg.Username,
		arg.Groupname,
		arg.Priority,
		arg.ID,
	)
}

const updateUserByProfile = `-- name: UpdateUserByProfile :execresult
UPDATE radcheck SET value = ? WHERE id = ? AND attribute = "User-Profile"
`

type UpdateUserByProfileParams struct {
	Value string
	ID    uint32
}

func (q *Queries) UpdateUserByProfile(ctx context.Context, arg UpdateUserByProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserByProfile, arg.Value, arg.ID)
}

const updateUserByUserName = `-- name: UpdateUserByUserName :execresult
UPDATE radcheck SET username = ? WHERE id = ?
`

type UpdateUserByUserNameParams struct {
	Username string
	ID       uint32
}

func (q *Queries) UpdateUserByUserName(ctx context.Context, arg UpdateUserByUserNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserByUserName, arg.Username, arg.ID)
}
